base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name="index")
]

eeepvnawebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('informatica/', include('informatica.urls', namespace='informatica')),
    path('', include('base.urls', namespace='base'))
]

informatica/urls.py
from django.urls import path

from . import views

app_name = 'informatica'

urlpatterns = [
    path('', views.index, name="index"),
    path('noticias/', views.noticias, name="noticias"),
    path('noticias/<int:notice_id>', views.noticia, name="noticia"),
    path('sobre_o_curso/', views.sobre_o_curso, name="sobre_o_curso")
]

base/models.py
from django.db import models

# Create your models here.

informatica/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Notice(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100, blank=True)
    main_image = models.ImageField(upload_to='notices/images/')
    content = RichTextField(blank=True)
    author = models.CharField(max_length=100)
    publish_date = models.DateField(auto_now_add=True)
    notice_category = models.ForeignKey('Categoria', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'Noticia no. {self.id}'

class Categoria(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return f'{self.name}'


class HomeSlide(models.Model):
    image = models.ImageField(upload_to='homeCarousel/images/')
    title = models.CharField(max_length=300)
    text = models.CharField(max_length=72)
    noticia = models.ForeignKey('Notice', on_delete=models.CASCADE)

    def __str__(self):
        return f'Slide no. {self.id}'

base/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'base/index.html')

informatica/views.py
from django.shortcuts import render
from . import models


def index(request):
    noticias_recentes = models.Notice.objects.all().order_by('-id')[:10]
    slides = models.HomeSlide.objects.all()
    categorias = models.Categoria.objects.all()

    pesquisa = request.GET.get('news-querry')
    filter = request.GET.get('filter')

    if filter:
        if filter == 'Todas':
            noticias_recentes = models.Notice.objects.all().order_by('-id')[:10]
        else:
            noticias_recentes = models.Notice.objects.all().filter(notice_category__name=filter)[:10]

    return render(request, 'informatica/index.html', {
        'slides': slides,
        'noticias_recentes': noticias_recentes,
        'categorias': categorias,
        'filter': filter
    })


# Noticias
def noticias(request):
    noticias = models.Notice.objects.all().order_by('-id')
    noticias_recentes = models.Notice.objects.all().order_by('-id')[:5]
    
    return render(request, 'informatica/noticias.html', {
        'noticias': noticias,
        'noticias_recentes': noticias_recentes
    })

# Noticia (Noticias/<id>)
def noticia(request, notice_id):
    noticias = models.Notice.objects.all().order_by('-id')
    noticias_recentes = models.Notice.objects.all().reverse()[:5]

    return render(request, 'informatica/noticia.html', {
        'noticia': models.Notice.objects.get(id=notice_id),
        'noticias': noticias,
        'noticias_recentes': noticias_recentes
    })

# Sobre o Curso
def sobre_o_curso(request):
    return render(request, 'informatica/sobre_o_curso.html')

# Sobre a escola
def sobre_a_escola(request):
    return render(request, 'informatica/sobre_a_escola.html')

base/templates/base/index.html
{% extends 'base/layout.html' %}


{% block head %}
    <style>
	* {
		margin: 0;
		padding: 0;
		box-sizing: border-box;
		box-shadow: none;
	}
	body {
		background: #181a17;
	}
	section {
		display: flex;
		flex-direction: column;
		padding: 32px;
		gap: 16px;
	}
	h1 {
		font-size: 2.5em;
		color: #e7eae5;
	}
	p {
		font-size: 1.25em;
		color: #d0d5cb;
		margin-bottom: 16px;
	}
	a {
		font-size 1.25em;
		background: #67832e;
		color: #e7eae5;
		padding: 8px 16px;
		text-decoration: none;
		width: fit-content;
		border-radius: 8px;
	}
    </style>
{% endblock %}

{% block body %}
    <section>
   	 <h1>Este site está em construção</h1>
   	 <p>O site oficial da escola EEEP Valter Nunes de Alencar estará pronto em breve!</p>
   	 <a href="{% url 'informatica:index' %}">Visitar o curso de informatica</a>
    </section>
{% endblock %}

base/templates/base/layout.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EEEP Valter Nunes de Alencar</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

informatica/templates/informatica/index.html
{% extends 'informatica/layout.html' %}
{% load static %}

{% block head %}
<script src="{% static 'informatica/scripts/index.js' %}"></script>
<link rel="stylesheet" href="{% static 'informatica/styles/index.css' %}">
<title> Informática - EEEP Valter Nunes de Alencar </title>
{% endblock %}

{% block top_header %}
<header>
    <span class="social">
        <a target="_blank" href="https://www.facebook.com/inforedes.eeepvna/"><i class="mdi mdi-facebook"></i></a>
        <a target="_blank" href="https://www.instagram.com/informatica.eeepvalter/"><i class="mdi mdi-instagram"></i></a>
        <a target="_blank" href="https://github.com/informatica-eeepvna/"><i class="mdi mdi-github"></i></a>
        <a href="#"><i class="mdi mdi-youtube"></i></a>
        <div class="refs">
            <a href="#">Site EEEP Valter Nunes</a>
        </div>
    </span>
</header>
{% endblock %}

{% block body %}
<main>
    <section id="inicio">
        <div class="home-carousel swiper">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <img class="slide-image" src="{% static 'informatica/images/inforarte.png' %}" alt="Imagem do curso">
                    <div class="slide-content">
                        <h1>Informática - EEEP Valter Nunes de Alencar</h1>
                        <p>Seja bem vindo ao curso de Informática da EEEP Valter Nunes de Alencar! Aqui você encontrará
                            as informações atualizadas e definições do que este curso tem a lhe oferecer e ajudar na preparação para este imenso
                            mercado de trabalho no ramo da tecnologia.</p>
                            <a href="{% url 'informatica:sobre_o_curso' %}">Saiba Mais</a>
                        </div>
                    </div>
                {% if slides %}
                {% for slide in slides %}
                <div class="swiper-slide">
                    <img class="slide-image" src="{{ slide.image.url }}" alt="slide.image | safe">
                    <div class="slide-content">
                        <h1>{{ slide.title }}</h1>
                        <p>{{ slide.text }}</p>
                        <a href="{% url 'informatica:noticia' slide.noticia.id %}">Saiba Mais</a>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="swiper-pagination"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    </section>
    <section id="principais-noticias">
        <div class="news-info">
            <form method="get" class="search-news">
                <input type="text" id="news-querry" name="news-querry"
                    placeholder="Pesquise algo sobre o curso: notícias, eventos, etc.">
                <input type="submit" id="submit-news-querry" value="Pesquisar">
            </form>
            <h1>Notícias recentes</h1>
            <div class="swiper news-carousel">
                <span class="navigation">
                    <span class="swiper-buttons">
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </span>
                    <span class="filters-container">
                        <form id="filters-form" action="{% url 'informatica:index' %}" method="get">
                            <select name="filter" class="filters">
                                <option value="Todas" class="filter-option">Todas</option>
                                {% for filter in categorias %}
                                    <option value="{{filter}}" class="filter-option">{{filter}}</option>
                                {% endfor %}
                            </select>
                            <input type="submit" value="Filtrar" class="submit-filter">
                        </form>
                    </span>
                </span>
                <div class="swiper-wrapper news-slide-wrapper">
                    {% if noticias_recentes %}
                    {% for noticia in noticias_recentes %}
                    <a href="{% url 'informatica:noticia' noticia.id %}" class="swiper-slide news-slide {{noticia.notice_category}}">
                        <img class="slide-image" src="{{ noticia.main_image.url }}"
                            alt="{{ noticia.main_image.url | safe }}">
                        <div class="slide-content">
                            <div class="info">
                                <div class="data">
                                    <p>{{ noticia.author }}</p>
                                    <span class="tags">
                                        <p class="tag-{{noticia.notice_category}}">{{ noticia.notice_category }}</p>
                                    </span>
                                </div>
                                <h1>{{ noticia.title }}</h1>
                                <p>{{ noticia.publish_date }}</p>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                    {% else %}
                    <div class="swiper-slide none news-slide">
                        <h1>Não há notícias recentes desse tema.</h1>
                        <a href="{% url 'informatica:noticias' %}">Acesse todas as notícias <i class="mdi mdi-arrow-right-thin"></i></a>
                    </div>
                    {% endif %}
                </div>
            </div>
            <a href="{% url 'informatica:noticias' %}">Mais notícias</a>
    </section>
    <section id="sobre-o-curso">
        <div class="geral-info">
            <div class="monitor">
                <iframe src="https://www.youtube.com/embed/vesmUTYheJ4" title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
                <div class="suporte"></div>
                <div class="base"></div>
            </div>
            <article>
                <h1>Sobre o curso</h1>
                <p>O curso técnico em informática da EEEP Valter Nunes de Alencar conta com uma excelente grade curricular e profissionais altamente qualificados
                    para o ensino e preparo no grande marcado de trabalho e mundo da tecnologia.
                    O curso conta com diversos eventos exclusivos, os quais são muito bem preparados e programados para os alunos do curso, o que torna o curso ainda mais atrativo e qualificado em todos os sentidos.
                </p>
                <p>Neste vídeo ao lado você pode observar e apreciar a cobertura do Corujão da Informática 4.0, que mostra as principais atrações do evento e sua realização.</p>
                <a href="{% url 'informatica:sobre_o_curso' %}">Saiba mais</a>
            </article>
        </div>
    </section>
</main>
{% endblock %}

{% block js %}
{% endblock %}

</html>

informatica/templates/informatica/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Victor Renan Alves de Oliveira">
    <!--Dependencias-->
    <script src="{% static 'informatica/libraries/Jquery-3.6/jquery-3.6.1.js' %}"></script>
    <script src="{% static 'informatica/libraries/Swiper-8.4/swiper-bundle.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'informatica/libraries/Swiper-8.4/swiper-bundle.min.css' %}">
    <link rel="icon" href="{% static 'informatica/images/infor-logo.png' %}">
    <link rel="stylesheet" href="{% static 'informatica/libraries/MaterialDesignIcons-6.9/css/materialdesignicons.min.css' %}">
    <!--Css e JS-->
    <script src="{% static 'informatica/scripts/menu.js' %}"></script>

    {% block head %}
    {% endblock %}

</head>

<body>

    {% block top_header %}
    {% endblock %}

    <nav id="nav-bar">
	    <a class="logo" href="{% url 'informatica:index' %}">
            <img src="{% static 'informatica/images/infor-logo.png' %}" alt="Logo de Informática">
            <h1><strong>#</strong>Informática</h1>
        </a>
        <i class="mdi mdi-menu menu"></i>
        <span class="nav-list">
            <a class="nav-item item-index" href="{% url 'informatica:index' %}">Home</a>
            <a class="nav-item item-sobre-o-curso" href="{% url 'informatica:sobre_o_curso' %}">Sobre o curso</a>
            <a class="nav-item" href="javascript:void(0);">Sobre a escola</a>
            <a class="nav-item item-noticias" href="{% url 'informatica:noticias' %}">Notícias</a>
            <a class="nav-item" href="{% url 'admin:index' %}">Acesso restrito</a>
        </span>
    </nav>

    {% block body %}
    {% endblock %}

    <footer>
        <div class="references">
            <span class="navigation">
                <img src="{% static 'informatica/images/infor-logo.png' %}" alt="Logo de Informática">
                <a class="nav-item" href="{% url 'informatica:index' %}">Home</a>
                <a class="nav-item" href="{% url 'informatica:sobre_o_curso' %}">Sobre o curso</a>
                <a class="nav-item" href="javascript:void(0);">Sobre a escola</a>
                <a class="nav-item" href="{% url 'informatica:noticias' %}">Notícias</a>
                <a class="nav-item"href="{% url 'admin:index' %}">Acesso restrito</a>
            </span>
            <span class="social">
                <a href="#"><i class="mdi mdi-facebook"></i></a>
                <a href="#"><i class="mdi mdi-instagram"></i></a>
                <a href="#"><i class="mdi mdi-github"></i></a>
                <a href="#"><i class="mdi mdi-youtube"></i></a>
            </span>
        </div>
        <div class="information">
            <p>&copy;2022 - EEEP Valter Nunes de Alencar, Curso de Informática</p>
            <p><strong>Professor Coordenador de Curso:</strong> Luis Lourenço de Oliveira Filho</p>
            <p><strong>Programador:</strong> Victor Renan Alves de Oliveira</p>
            <p><strong>Colunistas:</strong> Ana V. Castro & Ramon M. Alves</p>
            <p>informatica.eeepvna@gmail.com</p>
        </div>
    </footer>
    {% block js %}
    {% endblock %}
</body>

</html>

informatica/templates/informatica/noticia.html
{% extends 'informatica/layout.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" href="{% static 'informatica/styles/noticia.css' %}">
    <title>Criação do site do curso de informática | Informatica - EEEP VNA</title>
{% endblock %}


{% block body %}
<div id="content-box">
    <main>
        <section id="notice-head">
            <h1>{{ noticia.title | safe }}</h1>
            <p>{{ noticia.subtitle }}</p>
            <img src="{{ noticia.main_image.url }}" alt="{{noticia.main_image | safe}}">
            <div>
                <div class="metadata">
                    <p><i class="mdi mdi-clock-outline"></i>{{ noticia.publish_date }}</p>
                    <em class="author">{{ noticia.author }}</em>
                </div>
                <span class="social">
                    <a href="#"><i class="fa-brands fa-facebook"></i></a>
                    <a href="#"><i class="fa-brands fa-instagram"></i></a>
                    <a href="#"><i class="fa-brands fa-github"></i></a>
                    <a href="#"><i class="fa-brands fa-youtube"></i></a>
                </span>
            </div>
        </section>
        <section id="notice-body">
            <article>
                {{ noticia.content | safe }}
            </article>
        </section>
    </main>
    <aside>
        <section id="indice-noticias">
            <div id="mais-vistas">
                <h1>Notícias mais Vistas</h1>
                <div class="notices-list">
                {% for noticia in noticias_recentes %}
                <article class="notices-list-notice">
                    <a href="{% url 'informatica:noticia' noticia.id %}">
                        <img src="{{ noticia.main_image.url }}" alt="{{ noticia.main_image.url | safe }}">
                        <div class="notice-info">
                            <h1>{{ noticia.title }}</h1>
                            <p>{{ noticia.subtitle }}</p>
                        </div>
                    </a>
                </article>
                {% endfor %}
                </div>
            </div>
        </section>
    </aside>
</div>
{% endblock %}
</html>

informatica/templates/informatica/noticias.html
{% extends 'informatica/layout.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'informatica/styles/noticias.css' %}">
<title>Notícias</title>
{% endblock %}

{% block body %}
<div id="main-content">
    <main>
        <section id="noticias">
            {% for noticia in noticias %}
            <article class="notice">
                <a href="{% url 'informatica:noticia' noticia.id %}" class="notice-link">
                    <div class="notice-image-container">
                        <img class="notice-image" src="{{ noticia.main_image.url }}" alt="Asdf">
                    </div>
                    <div class="notice-info">
                        <div class="info-content">
                            <div class="data">
                                <p>{{ noticia.publish_date }}</p>
                                <h1>{{ noticia.title }}</h1>
                                <h2>{{ noticia.subtitle }}</h2>
                            </div>
                        </div>
                    </div>
                </a>
            </article>
            {% endfor %}
        </section>
    </main>
    <aside>
        <section id="indice-noticias">
            <div class="recente">
                <h1>Recente</h1>
                <article>
                    <iframe style="width:100%;height:100%;" src="https://www.youtube.com/embed/s9xLUzE8PZs" 
			    title="YouTube video player" frameborder="0" 
			    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
		    </iframe>
                </article>
            </div>
            <div class="social">
                <h1>Redes Sociais</h1>
                <article class="social-icons">
                    <a href="#"><i class="mdi mdi-facebook"></i></a>
                    <a href="#"><i class="mdi mdi-instagram"></i></a>
                    <a href="#"><i class="mdi mdi-github"></i></a>
                    <a href="#"><i class="mdi mdi-youtube"></i></a>
                </article>
            </div>
            <div id="mais-vistas">
                <h1>Mais Vistas</h1>
                <div class="notices-list">
                    {% for noticia in noticias_recentes %}
                    <article class="notices-list-notice">
                        <a href="{% url 'informatica:noticia' noticia.id %}">
                            <img src="{{ noticia.main_image.url }}" alt="{{ noticia.main_image.url | safe }}">
                            <div class="notice-info">
                                <p>{{ noticia.publish_date }}</p>
                                <h1>{{ noticia.title }}</h1>
                                <h2>{{ noticia.subtitle }}</h2>
                            </div>
                        </a>
                    </article>
                    {% endfor %}
                </div>
            </div>
        </section>
    </aside>
</div>
{% endblock %}

</body>

</html>